Read std mean from file
IBM/terratorch pull request #61
Opened 2024-07-26 18:21 UTC by Joao-L-S-Almeida

As the number of bands can be considerably large, it could be more convenient to input mean and std info via text files.

2024-07-29 12:14 UTC, CarlosGomes98 requested changes

2024-07-29 12:14 UTC, CarlosGomes98 commented on terratorch/datamodules/generic_scalar_label_data_module.py
> +    elif type(str): # It can be the path for a file
prefer `isinstance over `type`

2024-07-29 12:14 UTC, CarlosGomes98 commented on terratorch/datamodules/generic_scalar_label_data_module.py
> +def load_from_file_or_attribute(value:list[float] | str):
weird spacing in argument

2024-07-29 12:14 UTC, CarlosGomes98 commented on terratorch/datamodules/generic_scalar_label_data_module.py
> +            raise Exception("It seems that {value} does not exist or is not a file.")
Missing f string. Also, exception messages are usually in a more imperative tone, in this case I would remove "It seems that"

2024-07-29 16:57 UTC, Joao-L-S-Almeida commented
@CarlosGomes98 They were solved.

2024-07-30 08:54 UTC, CarlosGomes98 reviewed
the same issues were present in the `pixel_wise`. Once these are also fixed should be good to go :)

2024-07-30 08:54 UTC, CarlosGomes98 commented on terratorch/datamodules/generic_pixel_wise_data_module.py
> +            raise Exception("It seems that {value} does not exist or is not a file.")
same issue as for the scalar_label. Probably makes sense to make this a common function both use.

2024-07-30 08:54 UTC, CarlosGomes98 commented on terratorch/datamodules/generic_pixel_wise_data_module.py
> +def load_from_file_or_attribute(value:list[float] | str):
spacing

2024-07-30 12:51 UTC, Joao-L-S-Almeida commented on terratorch/datamodules/generic_pixel_wise_data_module.py
> +def load_from_file_or_attribute(value:list[float] | str):
Solved.

2024-07-30 14:20 UTC, CarlosGomes98 approved these changes

2024-07-30 14:31 UTC, merged